- hosts: linux
  vars:
    test: welcome to anible training
    Test: welcome
  tasks:
  - name: print variable
    debug:
      msg: "{{ test }}"
  - name: print another variable
    debug:
      msg: "{{ Test }}"
